import: definition.yaml

concurrency:
  task:
    incident_analysis: 1 # number of task workers for each task
  agent:
    incident_analyzer: 1 # number of task workers for each agent

assignments: # List[Assignment] | Assignment
  - agent: # "task": List[str] | str ,  "agent": List[str] | str
      - incident_analyzer
    task:
      - incident_analysis

output: "outputs/{TIMESTAMP}"
